package types

// PacketID represents different packet types
type PacketID uint16

const (
	// Packet IDs matching the C++ implementation
	CHECK_VERSION PacketID = iota
	PLAYER_CONNECTED
	PLAYER_DISCONNECTED
	PLAYER_ONFOOT
	PLAYER_BULLET_SHOT
	PLAYER_HANDSHAKE
	PLAYER_PLACE_WAYPOINT
	PLAYER_GET_NAME
	VEHICLE_SPAWN
	PLAYER_SET_HOST
	ADD_EXPLOSION
	VEHICLE_REMOVE
	VEHICLE_IDLE_UPDATE
	VEHICLE_DRIVER_UPDATE
	VEHICLE_ENTER
	VEHICLE_EXIT
	VEHICLE_DAMAGE
	VEHICLE_COMPONENT_ADD
	VEHICLE_COMPONENT_REMOVE
	VEHICLE_PASSENGER_UPDATE
	PLAYER_CHAT_MESSAGE
	PED_SPAWN
	PED_REMOVE
	PED_ONFOOT
	GAME_WEATHER_TIME
	PED_ADD_TASK
	PED_REMOVE_TASK
	PLAYER_KEY_SYNC
	PED_DRIVER_UPDATE
	PED_SHOT_SYNC
	PED_PASSENGER_UPDATE
	PLAYER_AIM_SYNC
	VEHICLE_CONFIRM
	PED_CONFIRM
	PLAYER_STATS
	REBUILD_PLAYER
	RESPAWN_PLAYER
	ASSIGN_VEHICLE
	MASS_PACKET_SEQUENCE
	START_CUTSCENE
	SKIP_CUTSCENE
	OPCODE_SYNC
	ON_MISSION_FLAG_SYNC
	UPDATE_ENTITY_BLIP
	REMOVE_ENTITY_BLIP
	ADD_MESSAGE_GXT
	REMOVE_MESSAGE_GXT
	CLEAR_ENTITY_BLIPS
	PLAY_MISSION_AUDIO
	UPDATE_CHECKPOINT
	REMOVE_CHECKPOINT
	ENEX_SYNC
	CREATE_STATIC_BLIP
	PACKET_ID_MAX
)

// Vector3 represents a 3D position/vector
type Vector3 struct {
	X, Y, Z float32
}

// PlayerID represents a unique player identifier
type PlayerID int32

// PedID represents a unique pedestrian identifier
type PedID int32

// VehicleID represents a unique vehicle identifier
type VehicleID int32

// Server version information
const (
	ServerVersion    = "0.1.1"
	ProtocolVersion  = 1
	MinClientVersion = "0.1.1"
)

// NetworkEntityType represents different types of network entities
type NetworkEntityType uint8

const (
	NETWORK_ENTITY_TYPE_PLAYER NetworkEntityType = iota
	NETWORK_ENTITY_TYPE_NOTHING
	NETWORK_ENTITY_TYPE_BUILDING
	NETWORK_ENTITY_TYPE_VEHICLE
	NETWORK_ENTITY_TYPE_PED
	NETWORK_ENTITY_TYPE_OBJECT
	NETWORK_ENTITY_TYPE_DUMMY
	NETWORK_ENTITY_TYPE_NOTINPOOLS
)

// Server configuration constants
const (
	MaxPlayers = 4095 // Maximum number of players/connections (matching C++ MAX_SERVER_PLAYERS)
)
